### ISSUE TITLE
Move project to the new OF version

### ISSUE THREAD

**Issue by GordeyChernyy** [GordeyChernyy/DrawingTool#13]
Hey @stevelackermann and @anirudh-eka, I moved all project to the new [OF version](http://www.openframeworks.cc/versions/v0.9.0/of_v0.9.0_osx_release.zip). Some of the previous addons doesn't work anymore, so I've removed them. There are many useful features in 0.9 for this project:
makefiles works well, now it's a time to get rid of the xcode
better hinting and kerning for TrueType, so I've removed FTGL
OpenGL ofFrameBuffer which will be very useful for fbo cropping 
there is a whole list of changes on [OF blog](http://blog.openframeworks.cc/)

**Comment by ghost** [comment]
Sweet!  I'm (still) wrapping up the stuff my edits, I'll probably port them
to your commit before I commit.
