### ISSUE TITLE
Create parameter manager

### ISSUE THREAD

**Issue by GordeyChernyy** [GordeyChernyy/DrawingTool#6]
I'm working on putting all parameters into class `ParameterManager`. Also have idea to create new interface behavior using `ofParameter` class.

**Comment by anirudh-eka** [comment]
+1 :)

**Comment by GordeyChernyy** [comment]
Done in this commit. https://github.com/GordeyChernyy/DrawingTool/commit/40f825301383f97b2caba48248d4c113f1a754ff
