### ISSUE TITLE
Clear canvas/image functionality not working

### ISSUE THREAD

**Issue by anirudh-eka** [GordeyChernyy/DrawingTool#7]
@GordeyChernyy can you confirm this? I press space like the direction says and it doesn't get cleared...

**Comment by GordeyChernyy** [comment]
I am working on it. I need update all information about behavior and yeah, there is no clear functionality yet.

**Comment by GordeyChernyy** [comment]
I fixed it in latest commit, forgot to place #7 label in commit message.

**Comment by anirudh-eka** [comment]
if it's your last commit you can do `git commit --amend` and change the message
