### ISSUE TITLE
Timeline design

### ISSUE THREAD

**Issue by GordeyChernyy** [GordeyChernyy/DrawingTool#9]
@stevelackermann is it possible to adjust parameters for text vertical position? Can't find parameter for it

**Comment by ghost** [comment]
Is this what you're looking for? (From timeline.cpp:136)

// Draws a number line with the frame numbers
// This function returns immediately except 1 out of FRAME_NUM_GRANULARITY times
void Timeline::drawFrameNum(int x, int frame_num) {
    if (frame_num % FRAME_NUM_GRANULARITY != 0) {
        return;
    }
    int y = _y + _height; //TODO: This is a hack becaue it looked right, make this based on FRAME_SIZE
    string s;
    ostringstream convert;
    convert << frame_num;
    s = convert.str();
    ofSetColor(ofColor::black);
    font.drawString(s, x-font.getWidth(s)/2, y);
}

**Comment by GordeyChernyy** [comment]
How to move all timeline down ?

**Comment by ghost** [comment]
When the timeline is created, you pass it (x, y) coordinates.  That's where the timeline's top left corner will be drawn (at the x,y coordinates).
So change this (ofApp.cpp:11) 

my_timeline.setup(ofGetWidth() / 8, ofGetWindowHeight() \* .75, ofGetWindowWidth() \* (6.0/8.0), ofGetWindowHeight() \* .2);

to be:
my_timeline.setup(NEW_X, NEW_Y, NEW_WIDTH, NEW_HEIGHT)
